version: "3.8"
services:
  redis:
    image: redis
    container_name: site_directory_redis
    restart: always
  nginx:
    image: nginx:stable-alpine
    container_name: site_directory_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./media:/code/media:ro
      - ./static_collected:/code/static_collected:ro
    depends_on:
      - web
    networks:
      - default
      - swag
  web:
    build: .
    container_name: site_directory_web
    restart: always
    environment:
      - ENVIRONMENT=docker
      - URL_PREFIX=
      - DEBUG=false
#    command: python3 manage.py runserver 0.0.0.0:8000
    command: uwsgi uwsgi.ini
    volumes:
      - .:/code
    depends_on:
      - redis
    networks:
      - default

networks:
  default:
    name: site_directory
  swag:
    name: swag
    external: true