# Generated by Django 4.1.7 on 2023-02-28 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='说明')),
            ],
            options={
                'verbose_name': '网站分类',
                'verbose_name_plural': '网站分类',
            },
        ),
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='链接')),
            ],
            options={
                'verbose_name': '链接',
                'verbose_name_plural': '链接',
            },
        ),
        migrations.CreateModel(
            name='WebSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='说明')),
                ('url', models.URLField(verbose_name='链接')),
                ('category', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='website.category')),
                ('extra_urls', models.ManyToManyField(to='website.url')),
            ],
            options={
                'verbose_name': '网站',
                'verbose_name_plural': '网站',
            },
        ),
    ]
