# Generated by Django 4.1.7 on 2023-03-19 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_category_created_time_category_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='rank',
            field=models.PositiveIntegerField(default=99, help_text='数字越小，排越前', verbose_name='排序'),
        ),
        migrations.AddField(
            model_name='website',
            name='rank',
            field=models.PositiveIntegerField(default=99, help_text='数字越小，排越前', verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='website',
            name='category',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='website.category', verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='website',
            name='extra_urls',
            field=models.ManyToManyField(blank=True, to='website.url', verbose_name='更多链接'),
        ),
    ]
